language: perl
sudo: false

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

services:
  - mysql

cache:
  directories:
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/

before_install:
    - mysql -uroot -e "grant all privileges on test.* to 'travis'@'localhost' identified by 's3kr1t'"
    - mysql -uroot -e "grant all privileges on test.* to 'travis'@'127.0.0.1' identified by 's3kr1t'"

install:
  - cpanm --notest --quiet Dist::Zilla
  - cpanm -v DBD::mysql@4.033
  - cpanm --notest Test::mysqld
  - cpanm --notest DBIx::Class::InflateColumn::Serializer
  - cpanm --notest Net::EmptyPort
  - cpanm --notest DBIx::Class::Schema::Loader
  - cpanm --notest DateTime::Format::SQLite
  - cpanm --notest DateTime::Format::MySQL
  - cpanm --notest SQL::Translator
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test
